### ISSUE TITLE
psy-view on mistral

### ISSUE THREAD

**Issue by naveed-hzg** [psyplot/psy-view#16]
#### Problem description

[I got the following error while load a file on mistral: 
 psy-view tke_mean.nc
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-g260119'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
]

**Comment by Chilipp** [comment]
Hey @naveed-hzg! 

Thanks for reporting!

You're connecting with X11 from your Mac to mistral, right? Did you add the `-Y` option? (i.e. `ssh -Y <username>@mistral.dkrz.de`). 

If this does not help, could you try to add the following command?

```bash
mkdir -p ~/.config/psyplot
echo 'help_explorer.use_webengineview: false' > ~/.config/psyplot/psyplotguirc.yml
```
and run it again? I actually thought that I solved this issue for psy-view, but maybe I have to check it again :disappointed:

**Comment by naveed-hzg** [comment]
Hey  @Chilipp ,
not it works. 
do i need to run the 
echo "..." line every time when i log in ?

**Comment by Chilipp** [comment]
Glad to hear (and sad that this is still necessary...). Now, it adjusted you configuration permanently to not import the `PyQt5.QtWebEngineWidgets` at all (which is apparently the module that causes this issues). This module is not necessary for psy-view, but it is necessary for psyplot-gui if you want to use the HTML-rendered help.
