### ISSUE TITLE
psy-view version

### ISSUE THREAD

**Issue by Casthardi** [psyplot/psy-view#18]
An option
`psy-view --version`
would be great to show the current version of psy-view and would help to name the version for issues.

**Comment by Chilipp** [comment]
True. I'll add it

**Comment by Chilipp** [comment]
Hey @Casthardi . I thought about it one more and actually I am not sure anymore, what you would like. I'll add a `-V` option for the psy-view command but this will only reflect the current stable version (i.e. for the current development version, it will always be 0.0.1.dev0). If you want a detailed installation information, you should use `conda list -n psy-view | grep psy-view`. This will give you the exact version including the build number and a commit hash.

**Comment by Casthardi** [comment]
I actually meant this for stable versions. You are right, presently it is not really of use. I was not aware that the stable version is presently always 0.0.1.dev0. However, time will come, when it matters.

**Comment by Chilipp** [comment]
True. I'll add it
