### ISSUE TITLE
mapplot/lineplot  

### ISSUE THREAD

**Issue by GeyerB** [psyplot/psy-view#24]
https://hub.gke.mybinder.org/user/psyplot-psy-view-t35hlyqi
rotated-pole-test.nc mit psyview
mapplot activ

#### Problem description
selecting a point for lineplot (lineplot opens)
selecting next point for lineplot from mapplot window - nothing happens. 
Reason is, that now 'line plot' as active in the control window, but it was not activated by me
![grafik](https://user-images.githubusercontent.com/57172205/81043948-94811880-8eb3-11ea-8306-1328f7118376.png)

**Comment by Chilipp** [comment]
I see, thanks for the investigation :) I'll fix it
