### ISSUE TITLE
colormap and colorbar

### ISSUE THREAD

**Issue by GeyerB** [psyplot/psy-view#25]
https://hub.gke.mybinder.org/user/psyplot-psy-view-t35hlyqi
rotated-pole-test.nc mit psyview
mapplot activ
**Problem description**
when customize axis 'colorbar'
![grafik](https://user-images.githubusercontent.com/57172205/81044122-ffcaea80-8eb3-11ea-990c-84efb41d9a44.png)
not 'Images, etc.' is active but 'axes' (which was not selected)

the change between colormaps is not every time successful
![grafik](https://user-images.githubusercontent.com/57172205/81044402-8da6d580-8eb4-11ea-8d0d-70f805c379b9.png)
or back to pastel2
![grafik](https://user-images.githubusercontent.com/57172205/81044467-b0d18500-8eb4-11ea-9800-8a58bd4044d7.png)

**Comment by Chilipp** [comment]
Hey @GeyerB! This is matplotlibs default built-in dialog and unfortunately it is not very stable. It should not be used to change the color settings in this case and I cannot do anything to make this work.
