### ISSUE TITLE
Value under cursor not consistent with data for ICON netCDF

### ISSUE THREAD

**Issue by Casthardi** [psyplot/psy-view#26]
In the example figure the values under the cursor shows the value 1 but must be nan.

![Voila_Capture 2020-05-05_02-27-48_PM](https://user-images.githubusercontent.com/9319607/81065939-9f03d800-8edc-11ea-847c-c6d9a2f1be9c.png)

[ocean_area.nc.zip](https://github.com/psyplot/psy-view/files/4580694/ocean_area.nc.zip)

**Comment by Chilipp** [comment]
Hey @Casthardi,

alright, I looked into your file and where your mouse is, there is not data (see the plot below)
![image](https://user-images.githubusercontent.com/9960249/81080998-af727d80-8ef1-11ea-8e5d-33df200e7f69.png)
Currently I am just looking for the closest grid cell center, I should also look if the plot contains the element at the given position.

**Comment by Casthardi** [comment]
Yes, in case there is no element it should show nan. Since the undefined values in the model area are also drawn in white, it ist hard to distinguish between inner and outer model area. Maybe the outer area can be coloured in e.g. "light grey". A similar problem (and even worse) will occur, if one uses a color bar that contains the color white. In that case the nan within the model area, the domain outside the model area and the value that is associated with white color all look the same.
