### ISSUE TITLE
high-res coastlines available?

### ISSUE THREAD

**Issue by Try2Code** [psyplot/psy-view#53]
hi again!

I noticed that the default coastlines are pretty coarse
![Figure_1](https://user-images.githubusercontent.com/681390/112977133-fe528280-9155-11eb-9599-f0c1015f08e8.png)

although it is just cosmetics: Is there an option to switch to a higher resolution coastline?

thx in advance!

**Comment by Chilipp** [comment]
hey @Try2Code! Sorry! I missed this issue.

yes, sure, this is already possible through the [`lsm` formatoption](https://psyplot.readthedocs.io/projects/psy-maps/en/latest/api/psy_maps.plotters.html#psy_maps.plotters.FieldPlotter.lsm) you can select different resolutions. One option would be `sp.update(lsm="10m")` for the highest available resolution.

In psy-view, you can do this through the projection settings dialog as in the screencast below.

does this help?


https://user-images.githubusercontent.com/9960249/114538794-0af5d100-9c54-11eb-8f6a-028b30b2f962.mp4

**Comment by Try2Code** [comment]
works perfectly - I missed that switch, sry
