### ISSUE TITLE
NEW FEATURE: Implement better selection of colormap

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-view#7]
#### Summary
There are way more colormaps available and it would be nice to select them independent from the current push button

#### Reason

more freedom

#### Detailed explanation
One possibility (and probably the easiest) would be to include a colormap dialog as it is already implemented for psy-simple (see Screenshot below) for the psyplot-gui. @tobstac: Do you think this is appropriate or do you have any other ideas?

#### Examples
![Screenshot from 2020-04-14 17-00-36](https://user-images.githubusercontent.com/9960249/79240089-9d149f00-7e71-11ea-9b0d-71487396211b.png)

**Comment by tobstac** [comment]
I'd like this solution. Maybe you could reduce the width of the dialog window somewhat by using much smaller boxes for the single colors or even show a continious colorbar. This way it might be possible for users to see their data and the possible colorbars at the same time, which could help when deciding for a colorbar or playing around.

**Comment by Chilipp** [comment]
In fact, the current dialog does this, it adjusts the colormap based on the number of levels. Note that there is no continuous colormap, usually a colormap is built upon 256 discrete colors. So if you choose a high number of colors (or `matplotlib.colors.Normalize`), you will see a _continuous_ colormap.

But my plan is, to redesign the current color settings dialog, and I'll add a preview for the chosen settings
