### ISSUE TITLE
CHANGE FEATURE: include more possibilities to select the projections

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-view#9]
#### Summary
The pushbutton to select the projection should be replaced or extended by a better control.

#### Reason
The button is rather uncomfortable and slow, and it limits the available projections. 

#### Detailed explanation
The basemap is handled via the [projection](https://psyplot.readthedocs.io/projects/psy-maps/en/latest/api/psy_maps.plotters.html#psy_maps.plotters.FieldPlotter.projection) formatoption that can have strings or [cartopy projections](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html). Now idea what the best solution is here to include it in the GUI. Any idea @tobstac?

**Comment by tobstac** [comment]
I would expect a drop down menu to work best, as it directly displays the available possibilities together with a fast way to choose one.

**Comment by Chilipp** [comment]
Alright. Do you think, it's enough to list the possibilities listed in the [projection formatoption docs](https://psyplot.readthedocs.io/projects/psy-maps/en/latest/api/psy_maps.plotters.html#psy_maps.plotters.FieldPlotter.projection)? I.e. `['cf', 'northpole', 'ortho', 'southpole', 'moll', 'geo', 'robin', 'cyl', 'stereo', 'near', 'rotated']`. Or should we add [all available projections from cartopy](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html)?

**Comment by tobstac** [comment]
Yes, I think this should be fine. After all, it would be easy for users to request an additional projection it the need arises.

**Comment by tobstac** [comment]
Just realized 'Yes' isn't a good answer for a 'This or that' question. I mean it should suffice to limit the projections to the ones listed in the docs.

**Comment by Chilipp** [comment]
Alright, I'll add a Toolbutton. When you click on it, you'll have the current behavior, when you hold it, you see a drop-down menu with the available projections. I'll let you know when this is done and it would be great if you could test it :smiley:
